[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 14.0

[font.normal]
style = "Regular"
family = "Maple Mono"

[env]
term = "xterm-256color"

[bell]
duration = 500

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_timeout = 0
unfocused_hollow = false
